### ISSUE TITLE
Tool installation

### ISSUE THREAD

**Issue by Hatem1405** [chenurawinrada/MOLOX-Instagram-Hacking-Tool#1]
Can you tell me the correct way to operate the tool

**Comment by chenurawinrada** [comment]
First, install these two python libraries,
1) colorama
* pip install colorama

2)instaloader
* pip install instaloader

If you don't have a dictionary file(a wordlist) then you have to create one or download one from Internet.

Then in terminal(Change the directory to where 'insta.py' can be found),

For linux,
* python3 insta.py

For windows,
* python insta.py
Or
* insta.py

**Comment by chenurawinrada** [comment]
After that,
When it asks for the target,

*Give the username of your target (the username which your target person used to log into his/her account)

*Then, it will ask for a dictionary file, so type the filename with the path. Ex;

C\users\dictionaries\my_dictionary.txt

*Then press enter. It will find the correct password for the target.
