### ISSUE TITLE
Hey i need help

### ISSUE THREAD

**Issue by iFushiguro** [chenurawinrada/MOLOX-Instagram-Hacking-Tool#3]
So i just don't know how to use this can you help me ?

**Comment by chenurawinrada** [comment]
This tool is using a dictionary attack.

If you  are using Windows, you can just use the exe file.
If you run the exe,
It will ask for a target, and a dictionary file.
Enter the username or account name as the target, then in next input, enter the dictionary file with path. Hit enter. After that password will be appeared.

Else, if you want tp use .py 
Then use,
python3 insta.py.
Steps are the same as above.
If you don't have necessary libraries, 
Then install them using pip.
Pip install instaloader
Pip install colorama
.

**Comment by iFushiguro** [comment]
Bro it's not working ![image](https://github.com/chenurawinrada/MOLOX-Instagram-Hacking-Tool/assets/138937827/52aa5d72-f4c5-44bb-973a-a56469a84541)

When i press enter the program just closes nothing happens

**Comment by chenurawinrada** [comment]
Here you have to type down the full username of the target (Which show on their insta acc) or their gmail (only if you know it). And also as the second input, the 'Dictionary file', you shout give the file name with the path. Then hit enter.
Example:
    Enter your target    : blabla@demoguy
     File (doctionary)    : D:\projectfiles\passwordlist\mylist.txt

**Comment by iFushiguro** [comment]
Yup that’s what i did , that’s the full username and the dictionary file ,
but i need to ask tho so i’m not confused about the file thing i have to
make a new text file then put in the route to it right ?

**Comment by chenurawinrada** [comment]
In the screenshot as  I can see you didn't add the .txt at the last if it is a txt file in here,
C:\Users\Mohammed Suhail\OneDrive\molox             <- In here, is this your txt file?

**Comment by iFushiguro** [comment]
Yea in the screenshot i didn’t but after it i did and it didn’t work the
app just closes when i hit enter

**Comment by chenurawinrada** [comment]
Try moving the txt file near to the program file, That means, try keeping the txt file near with the program(In the same directory)

**Comment by iFushiguro** [comment]
Ok i’ll try it out later and show the results , thx

**Comment by chenurawinrada** [comment]
Ok And thanks for letting me know about the error.

**Comment by iFushiguro** [comment]
Still ain’t working , i put the molox with the txt file in the same folder
and it didn’t work

**Comment by chenurawinrada** [comment]
Try using the .py file.

**Comment by iFushiguro** [comment]
Sadly i don’t know how

**Comment by chenurawinrada** [comment]
If you have installed python3, then, in the folder which contain "insta.py" open cmd.
Then,

Type this,

python insta.py

Then hit enter.
